version: '3'

networks:
  cesi.net:
    driver: 'bridge'

services:
  # Service Client Strapi
  cesi.strapi:
    image: 'strapi/strapi:latest'
    container_name: cesi_strapi
    env_file: .env
    restart: always
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    environment:
      DATABASE_CLIENT: ${DB_CLIENT}
      DATABASE_NAME: ${DB_NAME}
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
      DATABASE_USERNAME: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
    networks:
      - cesi.net

  # Service DB
  cesi.mongodb:
    image: 'mongo'
    container_name: 'cesi_mongodb'
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - '27017:27017'
    networks:
      - cesi.net

  # Service Administrer DB
  cesi.mongo-express:
    image: 'mongo-express'
    container_name: 'cesi_mongo-express'
    restart: always
    env_file: .env
    ports:
      - '8082:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: 'cesi.mongodb'
    networks:
      - cesi.net
